#!/bin/bash

set -e
if [[ ! -f ./releaser ]];then
  wget --quiet http://http.archive.ai-traders.com/releaser/1.0.3/releaser
fi
source ./releaser
if [[ ! -f ./docker-ops ]];then
  wget --quiet http://http.archive.ai-traders.com/docker-ops/0.2.3/docker-ops
fi
source ./docker-ops
# This goes as last in order to let end user variables override default values
releaser_init

image_name_no_registry="ansibleide"
image_name="docker-registry.ai-traders.com/${image_name_no_registry}"
base_image_name="docker-registry.base.ai-traders.com:5000/${image_name_no_registry}"
image_dir="./image"
imagerc_filename="imagerc"

command="$1"
case "${command}" in
  set_version)
      if [[ -n "$2" ]]; then
        next_version="$2"
        set_version_in_changelog "${changelog_file}" "${next_version}"
        set_next_oversion "${next_version}"
      else
        next_version=$(get_next_oversion)
        set_version_in_changelog "${changelog_file}" "${next_version}"
      fi
      exit $?
      ;;
  verify_version)
      verify_version_for_release
      exit $?
      ;;
  build)
      production_image_tag=$(get_last_version_from_changelog "${changelog_file}")
      docker_build_options="--build-arg this_image_name_arg=${image_name_no_registry} --build-arg this_image_tag_arg=${production_image_tag}"
      docker_build "${image_dir}" "${imagerc_filename}" "${image_name}" "$2"
      exit $?
      ;;
  itest)
      source_imagerc "${image_dir}"  "${imagerc_filename}"
      echo "Testing image: ${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}"
      # use the production ENTRYPOINT
      echo "IDE_DOCKER_IMAGE=\"${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}\"" > Idefile.to_be_tested
      # use real identity, it is needed to create vm in openstack
      echo "IDE_WORK=$(pwd)/test/integration/test_ide_work" >> Idefile.to_be_tested
      time bats "$(pwd)/test/integration/end_user/bats"
      exit $?
      ;;
  release)
      verify_version_for_release
      git_tag_from_oversion
      old_version=$(get_next_oversion)
      next_version=$(bump_patch_version "${old_version}")
      set_next_oversion "${next_version}"
      exit $?
      ;;
  publish_base)
      source_imagerc "${image_dir}"  "${imagerc_filename}"
      production_image_tag=$(get_last_version_from_changelog "${changelog_file}")
      testing_image_tag="${AIT_DOCKER_IMAGE_TAG}"

      log_info "testing_image_tag set to: ${testing_image_tag}"
      log_info "production_image_tag set to: ${production_image_tag}"
      if ! docker images ${AIT_DOCKER_IMAGE_NAME} | awk '{print $2}' | grep ${testing_image_tag} 1>/dev/null ; then
        # if docker image does not exist locally, then "docker tag" will fail,
        # so pull it. However, do not always pull it, the image may be not pushed
        # and only available locally.
        set -x -e
        docker pull "${AIT_DOCKER_IMAGE_NAME}:${testing_image_tag}"
      fi
      set -x -e
      # When tagging a docker image using docker 1.8.3, we can use `docker tag -f`.
      # When using docker 1.12, there is no `-f` option, but `docker tag`
      # always works as if force was used.
      docker tag -f "${AIT_DOCKER_IMAGE_NAME}:${testing_image_tag}" "${base_image_name}:${production_image_tag}" || docker tag "${AIT_DOCKER_IMAGE_NAME}:${testing_image_tag}" "${base_image_name}:${production_image_tag}"
      docker tag -f "${AIT_DOCKER_IMAGE_NAME}:${testing_image_tag}" "${base_image_name}:latest" || docker tag "${AIT_DOCKER_IMAGE_NAME}:${testing_image_tag}" "${base_image_name}:latest"
      if [[ "${dryrun}" != "true" ]];then
        docker push "${base_image_name}:${production_image_tag}"
        docker push "${base_image_name}:latest"
      fi
      set +x +e
      exit $?
      ;;
  publish)
      production_image_tag=$(get_last_version_from_changelog "${changelog_file}")
      validate_version_is_semver "${production_image_tag}"
      source_imagerc "${image_dir}" "${imagerc_filename}"
      docker_push "${AIT_DOCKER_IMAGE_NAME}" "${AIT_DOCKER_IMAGE_TAG}" "${production_image_tag}"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
